language: node_js
node_js: node
services: mongodb
env:
  - global:
    - secure: BgfcPNEX+RyWQ0VFVvP99fACSFnutohoy2Le9bINH5Shb35M4jZsrHKAIsZss3b9MfszD9Lvoxbw3idzDiAQuW+evJgtsOpPcbbDSUBxNyOUO8q3Bi+ccD1KihgD+omLsN5PSWD9pwuaGGGR7YCvL7Axzus4LyR9keuhsD760nq0G/CS340BYoan4qdtH9ioiAUxa5n+TcRRAcjcr6454lypvl38VhiEKJg012KYfT877a7DZwHu3IPG+bloJ13kLxRg199xrqt3ca+annGDlf8y9kdi4BrLofd3l21k2IAQ6M767W7J4/zrhnmtDX5Q+EFY28GA/mvWJB24/x/C3nHlSyHGolNxvZznUymDovSxzk4aYB5H1fmkv+7DnF+OnfdrYLRDq8HfJAjLBYPfii0dw+nw3zD5hiAfesAxvgOXpgMdiWKMJXbjAYNx318d+eRMzydkMPKiyDT4gRdkGSxL8A5VPL21ox4NCaQynegm6TuYiLIG9FX4YcRrbvFNLhJxrX15L0mLpA+x48yetOE9K4w7OMQMcyfbz49d02zdZDRKHPyTfH1QxP5Lx48+I6kPNTDRLre66IMfW/5BdCLYypUwzFiV0s49AVokpfZcOKIe3dbDYXAQsfm6hkVb/d8hRD5KeOg6+EXiIm7V8Z9S03qS5icpDEzPhPlu2Yk=
