language: node_js
node_js: node
services: mongodb
env:
  global:
    secure: a+pFzdJtBNU4YMt/hFKM4QRaoTFjjM1wkiiaFPY8slYmFk/zJ+YkNDLxRyN0niSZ7xWCIC4TS7XKiuX1OMndiI4Vj+FhQuM6o6KoYpOdIZI+FAguci164BusEKkF/NVAw5bwIU7nelwZ76FT2L/yOHqV1y7KRqiK6+466neFwrFStxPyBEFUCxRvlIdA20aKiOwrxsRxycIqFz98wHq2E/x8aqhRRFdh/FtJHRlig/JtSAd6IGD9Tje8M7NbiyEPilR42z55Gi7jJ2lyswlDAFWJZ999tDYLz4b9a+FzaV/LmTwrvLe1UuCoJGUrH3Z3qAM7EIxlNNZ1S0GDDA/AuA6EiBsC7mVDpItk5EAw2qepLZ1tehdmJLWnZOOetdwxSahVnaAfT227tgUprNxwmXnTrSkAw+D/BBikZcW1ULbZMCy0MecHaJ4G/StM/H4FqieQPFRhpSu1I5pzLYduFBniJez70sKjHMVfTJNKIF89o+PAO7NhR3Hw1o1Cx6kfE1oEzO/+kIDG75Ws9wmJcOYJlpGxTfZBYCA/aU1BQIp95kAnIFI9f9qxngXTkGw/vWFw+TY1po8AOnk3KMLnYs4IaudckEPoDj4a1ARjVOMvxBFFGbn6MjIR/2J+ge2AtYiNTmNUelMZFsPe3k8Xc+4V65lqjs3p4FT2JqVq4/M=
