language: node_js
node_js: node
services: mongodb
env:
  global:
    secure: egkxxdy+i8ED/XVMJ6eZgPml0PF9I5bEXgdKGzveb0P5CacZoVAAhh82D0IiErnf6y+BAQnCQo54lqEj80cL9glM6ngQHL4PC9qJ/1OfcS4/J/6PoPGigKf0LpQrD3j43jXRHAszuGTvyqhogwfiU1p15bpoXIlJoOuP3f5tPsX0FTqlf2Zdl3VXYCLrEWz8aC1GqjVteSxv/si/qgTbWs+v2RrOs/zlITRbImRoNKWpjxydf8CNp25jyJI94CN5qZvP9Vql3FCYY888Vvnqpdcxed8EvB3uO8WD/lWdPcyyQiviRGMrMADtyN5SJEJRYMQ3dlL8P4WQMKlHmHTkwpVuOFoKnxQzQ7ZLRfy/Ze1JnEtx6iDAgKpNcAqplk1AZ2ebjbV7WAi1Q6ZLzcRvZHwQ1KbKELEBGuff3P9Ihalq0rOk+ib2cnPLyOduCHFWS1NGKghVl9LZzaoThPFzClTvBiwHKE/ldUreU0/JSY3HhuCmlGG718UU0qN7uHQJrjr3fQJ+l69D/bl5NXt9DyHhs2/3BIgWMIjo2JXyAL6Y9qChqOUI8UCGS3tfhx6x2NJ1UXayjk8y0p8a90wegJxQi2c4E83/GrZAa4ex+U6V9HOMksjECDdYT6ZxbUcWsecc/Mx9iVG6ceQ6IGtS8SDvBNDmCzOaAlVIpxttfb0=
